src/django_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('posts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/posts/urls.py
from django.urls import path
from posts.views import BlogHome, BlogPostCreate, BlogListCategory, BlogPostDetailView

app_name = "posts"

urlpatterns = [
    path('', BlogHome.as_view(), name='home'),
    path('<str:category>/<str:slug>', BlogPostDetailView.as_view(), name='post'),
    path('category', BlogListCategory.as_view(), name='blog_category'),
    path('create', BlogPostCreate.as_view(), name='create'),
]

src/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse

# Create your models here.

User = get_user_model()


class Category(models.Model):
    name = models.CharField(max_length=36)
    slug = models.SlugField()

    def __str__(self):
        return self.name


def caroussel_view(request):
    # Récupérer les 3 articles les plus récents
    latest_posts = BlogPost.objects.order_by('-created_on')[:3]

    context = {
        'latest_posts': latest_posts
    }

    return render(request, 'caroussel.html', context)
class BlogPost(models.Model):
    title = models.CharField(max_length=255, unique=True, verbose_name="Titre")
    slug = models.SlugField(max_length=255, unique=True, blank=True)
    image = models.ImageField(upload_to='blog/', null=True, blank=True)
    category = models.ManyToManyField(Category)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    description = models.TextField(max_length=150)
    content = models.TextField(blank=True, verbose_name="Contenu")
    last_updated = models.DateTimeField(auto_now=True)
    created_on = models.DateField(blank=True, null=True)
    published = models.BooleanField(blank=False, null=True, verbose_name="Publié")

    class Meta:
        ordering = ['-created_on']
        verbose_name = "Article"

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)

        super().save(*args, **kwargs)

    def author_or_default(self):
        if self.author:
            return self.author.username
        return "L'auteur inconnu"

    def get_categories(self):
        return ", ".join(category.name for category in self.category.all())

    def get_category(self):
        first_category = self.category.first()
        if first_category:
            return first_category.slug
    @staticmethod
    def get_latest_posts():
        return BlogPost.objects.order_by('-created_on')[:3]

    def get_absolute_url(self):
        return reverse('posts:home')




src/posts/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy

from django.views.generic import ListView, CreateView, DetailView
from posts.models import BlogPost, Category
from django.http import JsonResponse



# Create your views here.
def latest_posts_context(request):
    return {
        'latest_posts': BlogPost.get_latest_posts(),
    }

class BlogHome(ListView):
    model = BlogPost
    context_object_name = "posts"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context
    def get_queryset(self):
        queryset = super().get_queryset()
        category_slug = self.request.GET.get('category')
        if category_slug:
            queryset = queryset.filter(category__slug=category_slug)
        return queryset



class BlogPostDetailView(DetailView):
    model = BlogPost
    context_object_name = 'post'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(category__slug=self.kwargs['category'], slug=self.kwargs['slug'])
        return queryset

class BlogListCategory(ListView):
    model = Category
    template_name = "category_list"
    context_object_name = "categories"

class BlogPostCreate(CreateView):
    model = BlogPost
    template_name = "posts/blogpost_create.html"
    fields = ['title','description', 'content', 'category', 'created_on' ]

src/posts/templates/posts/blogpost_create.html
{% extends 'base.html' %}

{% block title %}
  <title>Ajouter un article</title>
{% endblock %}

{% block content %}
  <h1>Ajouter un article</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Créer">
  </form>
{% endblock %}

src/posts/templates/posts/blogpost_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>Accueil du blog</title>
{% endblock %}

{% block content %}
    <div class="post_content">
        <div class="background-article">
            <div class="illustration_carou">
                {% if post.image %}
                <img src="{{ post.image.url }}" alt="{{ post.title }}">
                {% endif %}
                <div class="article_carou">
                    <div class="publication_carou">
                        <div class="categorie_carou">{{ post.get_categories }}</div>
                        <div class="author_carou">Publié par {{post.author}} le {{post.created_on|safe }}</div>
                    </div>
                    <div class="post_title_carou">
                        <h2>{{ post.title }}</h2>
                      </div>
                  </div>
              </div>
            </div>
        <div class="content">
            {{ post.content|safe }}
        </div>
    </div>

{% endblock %}

src/posts/templates/posts/blogpost_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>Accueil du blog</title>
{% endblock %}

{% block content %}
    {% include 'components/caroussel.html' %}
    <div class="title">
        <h1>Derniers articles</h1>
            <img src="/media/img/underline.png" alt="" class="underline">
    </div>

    <div id="categories_tags">
        <a href="#" class="category_tag" data-category="all">Tout</a>
        {% for category in categories %}
            <a href="#" class="category_tag" data-category="{{ category.name }}">{{ category.name }}</a>
        {% endfor %}
    </div>
    <script>

    </script>

    <div class="article_list">
        {% for post in posts %}
            {% if post.published == True %}
                <a href="{% url 'posts:post' category=post.get_category slug=post.slug %}">{% include 'components/post_card.html' %}</a>
            {% endif %}
        {% endfor %}
    </div>
    <script>
        // Écouteur d'événement pour les liens de catégorie
        const categoryLinks = document.querySelectorAll('.category_tag');
        const postCards = document.querySelectorAll('.post_card');

        categoryLinks.forEach(link => {
            link.addEventListener('click', (e) => {
                e.preventDefault();
                const selectedCategory = link.getAttribute('data-category');

                // Afficher ou masquer les articles en fonction de la catégorie sélectionnée
                postCards.forEach(card => {
                    const cardCategory = card.getAttribute('data-category');
                    if (selectedCategory === cardCategory || selectedCategory === 'all') {
                        card.style.display = 'flex';

                    } else {
                        card.style.display = 'none';
                    }
                });
            });
        });
    </script>
{% endblock %}

src/posts/templates/posts/category_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>Accueil du blog</title>
{% endblock %}

{% block content %}
    <div>
        <div class="title">
            <h1>Catégories</h1>
            <img src="/media/img/underline.png" alt="" class="underline">
        </div>
        <div class="category_list">
        {% for category in categories %}
            <div class="category_card">
                <h2>{{ category.name }}...</h2>
            </div>
        {% endfor %}
        </div>
    </div>
{% endblock %}

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    {% block title %}
    <title>Accueil du blog</title>
    {% endblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/header.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/caroussel.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/article.css' %}">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
<body>
{% include 'components/header.html' %}


<section id="blog">
    {% block content %}

    {% endblock %}
</section>

</body>
</html>

src/templates/components/caroussel.html
<div class="caroussel">
  <div class="previous"><img src="/media/img/larrow.png" alt="" class="arrow"></div>
  <div class="caroussel_img">
    {% for post in latest_posts %}
      {% if post.published == True %}
          <a href="{% url 'posts:post' category=post.get_category slug=post.slug %}">
              <div class="illustration_carou">
                  {% if post.image %}
                    <img src="{{ post.image.url }}" alt="{{ post.title }}">
                  {% endif %}
                  <div class="article_carou">
                      <div class="publication_carou">
                        <div class="categorie_carou">{{ post.get_categories }}</div>
                        <div class="author_carou">Publié par {{post.author}} le {{post.created_on|safe }}</div>
                      </div>
                      <div class="post_title_carou">
                        <h2>{{ post.title }}</h2>
                      </div>
                  </div>
              </div>
          </a>
      {% endif %}

    {% endfor %}
  </div>
  <div class="next"><img src="/media/img/rarrow.png" alt="" class="arrow"></div>
</div>
<div class="caroussel-dots">
   {% for post in latest_posts %}
      <div class="dot"></div>
   {% endfor %}
</div>
<script>
  $(document).ready(function() {
    $('.caroussel_img').slick({
      slidesToShow: 1,
      slidesToScroll: 1,
      prevArrow: $('.previous'),
      nextArrow: $('.next'),
    });
    // Gestion des dots
    $('.caroussel_img').on('afterChange', function(event, slick, currentSlide) {
      // Réinitialiser tous les dots
      $('.caroussel-dots .dot').removeClass('active');

      // Activer le dot correspondant à la diapositive actuelle
      $('.caroussel-dots .dot').eq(currentSlide).addClass('active');
    });

    // Gestion du clic sur un dot
    $('.caroussel-dots .dot').on('click', function() {
      // Récupérer l'index du dot
      var dotIndex = $(this).index();

      // Faire défiler le carrousel jusqu'à l'index du dot
      $('.caroussel_img').slick('slickGoTo', dotIndex);
    });
  });
  document.addEventListener("DOMContentLoaded", function() {
  const arrows = document.querySelectorAll(".caroussel .arrow");

  arrows.forEach(function(arrow) {
    arrow.addEventListener("mouseenter", function() {
      this.classList.add("filled");
    });

    arrow.addEventListener("mouseleave", function() {
      this.classList.remove("filled");
    });
  });
});

</script>

src/templates/components/footer.html
<footer>


</footer>

src/templates/components/header.html
{% load static %}
<header>
    <div class="menu">
        <a href="{% url 'posts:home' %}"><div class="menu_item"><img src="/media/img/header/home.png" alt="" class="home_img"> Accueil</div></a>
        <a href="{% url 'posts:blog_category' %}"><div class="menu_item">Catégories</div></a>
    </div>
    <a href=""><div class="account">Mon compte</div></a>
</header>

src/templates/components/post_card.html
<article class="post_card" data-category="{{ post.get_categories }}">
  <div class="illustration">
    {% if post.image %}
    <img src="{{ post.image.url }}" alt="">
    {% endif %}
    <div class="test">
      <div class="publication">
        <div class="categorie">{{ post.get_categories }}</div>
        <div class="author">Publié par {{post.author}} le {{post.created_on|safe }}</div>
      </div>
      <div class="post_title">
        <h2>{{ post.title }}</h2>
      </div>
    </div>
  </div>
  <div class="legend">
    <p> {{ post.description }}</p>
  </div>
</article>







